version: '3.7'
services:
  postgresql:
    image: repository.dimas-maryanto.com:8086/postgres:12.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
volumes:
  pg_data:
